# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin_login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
    ]
